"""Regenerate manuscript/latex/generated_numbers.tex from real outputs.

Every \\newcommand here is derived from a file this repo's pipeline actually
produced (data/raw, data/processed) or from the actual application source
(app/src/organs.ts) -- never hand-typed. Run this before every manuscript
compile (see manuscript/Makefile's `numbers` target).
"""
import re
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "data" / "processed"
ORGANS_TS = ROOT / "app" / "src" / "organs.ts"
OUT = ROOT / "manuscript" / "latex" / "generated_numbers.tex"


def macro(name: str, value) -> str:
    # LaTeX \newcommand names must be alphabetic only -- a digit silently breaks
    # everything after it in the compiled document (swallows \begin{document}).
    if not name.isalpha():
        raise ValueError(f"macro name {name!r} must be alphabetic only (no digits) for LaTeX")
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def main():
    organs_src = ORGANS_TS.read_text()
    n_organs = len(re.findall(r'^\s*id:\s*"', organs_src, flags=re.MULTILINE))
    n_organs_with_geom_citation = len(
        re.findall(r'geometryCitations:\s*\[\s*"', organs_src)
    )

    osd120 = pd.read_csv(PROCESSED / "OSD-120_root_flight_vs_ground_log2fc.csv", index_col=0)
    osd314 = pd.read_csv(PROCESSED / "OSD-314_seedling_microgravity_vs_1g_log2fc.csv", index_col=0)

    osd120_col = "log2fc_flight_vs_ground"
    osd314_col = "log2fc_microgravity_0g_vs_ground_1g"

    lines = [
        "% Auto-generated by scripts/03_manuscript_numbers.py -- do not hand-edit.\n",
        macro("NumOrgansModeled", n_organs),
        macro("NumOrgansWithGeometryCitation", n_organs_with_geom_citation),
        macro("NumGenesOsdOneTwentyZero", f"{len(osd120):,}"),
        macro("NumGroundSamplesOsdOneTwentyZero", int(osd120["n_ground"].iloc[0])),
        macro("NumFlightSamplesOsdOneTwentyZero", int(osd120["n_flight"].iloc[0])),
        macro("TopFoldChangeOsdOneTwentyZero", f"{osd120[osd120_col].max():.2f}"),
        macro("TopGeneOsdOneTwentyZero", osd120[osd120_col].idxmax()),
        macro("NumGenesOsdThreeFourteen", f"{len(osd314):,}"),
        macro("NumGroundSamplesOsdThreeFourteen", int(osd314["n_ground_1g"].iloc[0])),
        macro("NumMicrogSamplesOsdThreeFourteen", int(osd314["n_microgravity_0g"].iloc[0])),
        macro("TopFoldChangeOsdThreeFourteen", f"{osd314[osd314_col].max():.2f}"),
        macro("TopGeneOsdThreeFourteen", osd314[osd314_col].idxmax()),
    ]
    OUT.write_text("".join(lines))
    print(f"Wrote {OUT}")
    print("".join(lines))


if __name__ == "__main__":
    main()
