"""Full growth-animation render: one real day (Boyes et al. 2001 timeline, day 0 to
GROWTH_DAY_MAX) per output frame, camera on a slow continuous orbit, real Cycles
materials/lighting (blender/materials.py). Each frame's GEOMETRY is generated by
re-running the real TypeScript plant generator (buildGrowthSnapshot) via `npx tsx` -- not
interpolated in Blender -- so every frame is an independently correct, real-data-driven
snapshot.

Materials, lights, and camera are built ONCE and reused across frames (only the imported
plant mesh objects are cleared and re-imported each iteration). The first version of this
script rebuilt materials from scratch every frame, which crashed Cycles' Metal shader
compiler (BLI_mmap SIGBUS inside ccl::MetalKernelPipeline::compile) after ~9 frames --
forcing hundreds of redundant shader recompiles in one process was both wasteful and
apparently unstable. Diagnosed from the actual crash backtrace, not guessed.

Run: /Applications/Blender.app/Contents/MacOS/Blender --background --python \
       blender/render_growth_animation.py -- <num_frames> <start_frame> <end_frame> [samples]

start_frame/end_frame (inclusive) let a long render be resumed/chunked; omit to do the
whole range 0..num_frames-1. Frames already present on disk are skipped, so this script
can simply be re-run after an interruption without redoing finished work.
"""
import sys
import os
import math
import subprocess
import time
import bpy
from mathutils import Vector

sys.path.insert(0, "blender")
import materials as mat_lib

REPO_ROOT = os.getcwd()
GROWTH_DAY_MAX = 49.4  # Boyes et al. 2001 stage 6.90, flowering complete -- see growthStages.ts
TMP_GLB = "/tmp/growth_anim_frame.glb"
OUT_DIR = "blender/exports/animation_frames"
os.makedirs(OUT_DIR, exist_ok=True)

argv = sys.argv[sys.argv.index("--") + 1:]
num_frames = int(argv[0])
start_frame = int(argv[1]) if len(argv) > 1 else 0
end_frame = int(argv[2]) if len(argv) > 2 else num_frames - 1
samples = int(argv[3]) if len(argv) > 3 else 128

# Fixed camera framing, computed once from the MATURE plant so it doesn't jump around
# frame to frame -- growth should read as the plant filling more of a stable frame, not
# the camera chasing it.
mature_glb = "blender/exports/growth_day_mature_ref.glb"
subprocess.run(["npx", "tsx", "blender/export_growth_frame.ts", str(GROWTH_DAY_MAX), mature_glb], check=True, cwd=REPO_ROOT)

bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.import_scene.gltf(filepath=mature_glb)
mesh_objs = [o for o in bpy.data.objects if o.type == "MESH"]
world_corners = []
for o in mesh_objs:
    for corner in o.bound_box:
        world_corners.append(o.matrix_world @ Vector(corner))
min_co = [min(c[i] for c in world_corners) for i in range(3)]
max_co = [max(c[i] for c in world_corners) for i in range(3)]
CENTER = Vector([(min_co[i] + max_co[i]) / 2 for i in range(3)])
RADIUS = max(max_co[i] - min_co[i] for i in range(3)) / 2 or 1.0
GROUND_Y = min_co[1]
print(f"Camera framing: center={tuple(CENTER)} radius={RADIUS:.3f}")

# Remove the reference plant -- materials/lighting/ground/camera below are what persist;
# the actual per-frame plant gets imported fresh each iteration.
for o in mesh_objs:
    bpy.data.objects.remove(o, do_unlink=True)

# Build every material ONCE. Reusing the same material datablocks across frames (rather
# than calling build_*_material() again each iteration) is what avoids re-triggering
# Cycles' Metal shader compiler per frame.
leaf_mat = mat_lib.build_leaf_material()
petal_mat = mat_lib.build_leaf_material(name="PetalMaterial", base_color=(0.85, 0.85, 0.82), sss_color=(0.9, 0.9, 0.88))
stem_mat = mat_lib.build_stem_material()
root_mat = mat_lib.build_root_material()
silique_mat = mat_lib.build_stem_material(name="SiliqueMaterial", base_color=(0.5, 0.55, 0.25))
soil_mat = mat_lib.build_soil_material()
mat_lib.build_ground_plane(Vector((CENTER.x, GROUND_Y, CENTER.z)), RADIUS, soil_mat)
mat_lib.setup_lighting(CENTER, RADIUS)

cam_data = bpy.data.cameras.new("Camera")
cam_obj = bpy.data.objects.new("Camera", cam_data)
bpy.context.collection.objects.link(cam_obj)
bpy.context.scene.camera = cam_obj
cam_data.lens = 50

scene = bpy.context.scene
scene.render.engine = "CYCLES"
scene.cycles.samples = samples
scene.cycles.device = "GPU"
prefs = bpy.context.preferences.addons["cycles"].preferences
prefs.compute_device_type = "METAL"
prefs.get_devices_for_type("METAL")
for d in prefs.devices:
    d.use = True
scene.render.resolution_x = 1920
scene.render.resolution_y = 1080

t0 = time.time()
rendered = 0
for frame_idx in range(start_frame, end_frame + 1):
    out_path = f"{OUT_DIR}/frame_{frame_idx:04d}.png"
    if os.path.exists(out_path):
        continue  # resume support: don't redo a frame already on disk

    day = (frame_idx / (num_frames - 1)) * GROWTH_DAY_MAX
    subprocess.run(["npx", "tsx", "blender/export_growth_frame.ts", str(day), TMP_GLB], check=True, cwd=REPO_ROOT)

    bpy.ops.import_scene.gltf(filepath=TMP_GLB)
    new_meshes = [o for o in bpy.data.objects if o.type == "MESH" and o.name != "Plane"]
    mat_lib.apply_materials(leaf_mat, stem_mat, root_mat, petal_mat, silique_mat)

    # Slow continuous orbit: azimuth drifts across the whole animation, a real cinematic
    # move rather than a static turntable-free shot -- a technique choice, not data.
    progress = frame_idx / max(1, num_frames - 1)
    az = math.radians(20 + 40 * progress)
    el = math.radians(14)
    dist = RADIUS * 1.9
    cam_obj.location = CENTER + Vector((dist * math.cos(el) * math.sin(az), -dist * math.cos(el) * math.cos(az), dist * math.sin(el) + RADIUS * 0.15))
    look_dir = CENTER - cam_obj.location
    cam_obj.rotation_euler = look_dir.to_track_quat("-Z", "Y").to_euler()

    scene.render.filepath = out_path
    bpy.ops.render.render(write_still=True)

    # Remove this frame's imported plant objects (but not materials/lights/camera/ground)
    # before the next iteration.
    for o in new_meshes:
        mesh_data = o.data
        bpy.data.objects.remove(o, do_unlink=True)
        if mesh_data and mesh_data.users == 0:
            bpy.data.meshes.remove(mesh_data)

    rendered += 1
    elapsed = time.time() - t0
    avg = elapsed / rendered
    remaining = (end_frame - frame_idx)
    eta_min = avg * remaining / 60
    print(f"FRAME_DONE {frame_idx} day={day:.2f} elapsed={elapsed:.0f}s avg={avg:.1f}s/frame eta={eta_min:.1f}min")

print("ANIMATION_RENDER_COMPLETE")
