"""Full growth-animation render: one real day (Boyes et al. 2001 timeline, day 0 to
GROWTH_DAY_MAX) per output frame, real Cycles materials/lighting (blender/materials.py).
Each frame's GEOMETRY is generated by re-running the real TypeScript plant generator
(buildGrowthSnapshot) via `npx tsx` -- not interpolated in Blender -- so every frame is an
independently correct, real-data-driven snapshot.

v2 (director's pass): the camera is no longer one fixed framing computed from the mature
plant. It now re-frames on EACH frame's own actual above-ground bounding box (root meshes
excluded -- they're buried and would otherwise skew centering/distance toward a mostly-
invisible extent), with elevation/distance/lens/vertical-bias eased across a small set of
CAMERA_KEYFRAMES anchored at real Boyes stage days (see the growth-animation-v2 plan).
The keyframe TIMES reuse real data; the keyframe VALUES (how close, how high, what lens) are
a disclosed directorial choice, exactly like the leaf/organ emergence-window shape already
is. Depth of field is now enabled (physical aperture, focus tracking the current framing
target) -- the single biggest lever found for a photographic rather than CG look.

Materials, lights, and the ground are built ONCE and reused across frames (only the imported
plant mesh objects are cleared and re-imported each iteration). The first version of this
script rebuilt materials from scratch every frame, which crashed Cycles' Metal shader
compiler (BLI_mmap SIGBUS inside ccl::MetalKernelPipeline::compile) after ~9 frames --
forcing hundreds of redundant shader recompiles in one process was both wasteful and
apparently unstable. Diagnosed from the actual crash backtrace, not guessed.

Run: /Applications/Blender.app/Contents/MacOS/Blender --background --python \
       blender/render_growth_animation.py -- <num_frames> <start_frame> <end_frame> [samples]

start_frame/end_frame (inclusive) let a long render be resumed/chunked; omit to do the
whole range 0..num_frames-1. Frames already present on disk are skipped, so this script
can simply be re-run after an interruption without redoing finished work.
"""
import sys
import os
import math
import subprocess
import time
import bpy
from mathutils import Vector

sys.path.insert(0, "blender")
import materials as mat_lib

REPO_ROOT = os.getcwd()
GROWTH_DAY_MAX = 49.4  # Boyes et al. 2001 stage 6.90, flowering complete -- see growthStages.ts
TMP_GLB = "/tmp/growth_anim_frame.glb"
OUT_DIR = "blender/exports/animation_frames"
os.makedirs(OUT_DIR, exist_ok=True)

argv = sys.argv[sys.argv.index("--") + 1:]
num_frames = int(argv[0])
start_frame = int(argv[1]) if len(argv) > 1 else 0
end_frame = int(argv[2]) if len(argv) > 2 else num_frames - 1
samples = int(argv[3]) if len(argv) > 3 else 128

# Camera-style keyframes: (day, elevation_deg, distance_multiplier_of_that_frames_own_radius,
# lens_mm, vertical_look_bias_fraction_of_radius). Eased linearly between consecutive points.
# The DAYS reuse real Boyes et al. 2001 stage boundaries already driving the biology
# (growthStages.ts); the VALUES are a disclosed cinematography choice -- see the
# growth-animation-v2 plan for the reasoning behind each zone.
CAMERA_KEYFRAMES = [
    (0.0,   55.0, 3.4, 90.0,  0.15),   # steep, near-overhead macro lens looking down into the pot
    (6.0,   48.0, 2.8, 70.0,  0.12),   # still close/steep through cotyledon emergence
    (14.0,  30.0, 2.3, 50.0,  0.10),   # leveling out and rising as rosette leaves fill out
    (29.3,  20.0, 2.15, 50.0, 0.02),   # rosette complete; slight top-down bias for phyllotaxy
    (37.0,  16.0, 2.35, 50.0, -0.08),  # bolting underway; rising/pulling back to track the stem
    (49.4,  13.0, 2.05, 60.0, -0.18),  # final push-in bias toward the raceme for flower/silique detail
]
# A steep overhead angle is deliberate, not just an arbitrary starting value: the pot is a
# fixed, realistic mature-plant size (POT_RADIUS) even while the seedling itself is a few mm
# across, and a real test render at a shallow/low angle put the camera inside or grazing the
# pot's own rim, or (once floored back on total distance) so far back the shot read as sky,
# not a macro shot -- confirmed by actually rendering it, not guessed. Shooting down from
# close-above instead lets the camera get near the seedling while clearing the rim
# horizontally, matching how you'd actually photograph a seedling in a pot.


def camera_style_at_day(day: float):
    pts = CAMERA_KEYFRAMES
    if day <= pts[0][0]:
        vals = pts[0][1:]
    elif day >= pts[-1][0]:
        vals = pts[-1][1:]
    else:
        vals = None
        for (d0, *v0), (d1, *v1) in zip(pts, pts[1:]):
            if d0 <= day <= d1:
                t = (day - d0) / (d1 - d0)
                vals = tuple(a + (b - a) * t for a, b in zip(v0, v1))
                break
        if vals is None:
            vals = pts[-1][1:]
    return vals  # (elevation_deg, distance_multiplier, lens_mm, vertical_bias)


# The plant's collar (where root and shoot both originate) is always at local (0,0,0) by
# construction in geometry.ts, and Blender's glTF import preserves that as the world origin
# (confirmed directly: Root_primary.matrix_world.translation == (0,0,0) for every export) --
# so the ground plane's vertical position doesn't need to be derived from any bounding box.
# The previous version derived it from CENTER.z of the mature reference's FULL bbox
# (root included), which put the ground ~0.46 units below the true collar -- confirmed by a
# direct test render showing a small exposed root nub below the visible stem base. Anchoring
# directly to the real collar instead fixes that with no dependency on plant size or day.
GROUND_Z = -0.025

# Pot radius: a fixed value grounded in this session's own measured mature-plant extents
# (mature rosette half-width ~0.76 units, mature root horizontal half-spread ~0.47 units),
# not an arbitrary guess -- comfortably contains both with visible pot-rim margin.
POT_RADIUS = 0.9

# A single mature-reference bounding box is still computed once, ONLY to size the world
# lighting rig against the largest scale used across the whole animation.
mature_glb = "blender/exports/growth_day_mature_ref.glb"
subprocess.run(["npx", "tsx", "blender/export_growth_frame.ts", str(GROWTH_DAY_MAX), mature_glb], check=True, cwd=REPO_ROOT)

bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.import_scene.gltf(filepath=mature_glb)
mesh_objs = [o for o in bpy.data.objects if o.type == "MESH"]
world_corners = []
for o in mesh_objs:
    for corner in o.bound_box:
        world_corners.append(o.matrix_world @ Vector(corner))
min_co = [min(c[i] for c in world_corners) for i in range(3)]
max_co = [max(c[i] for c in world_corners) for i in range(3)]
MATURE_RADIUS = max(max_co[i] - min_co[i] for i in range(3)) / 2 or 1.0
print(f"Lighting sizing reference: mature radius={MATURE_RADIUS:.3f}, ground_z={GROUND_Z}")

for o in mesh_objs:
    bpy.data.objects.remove(o, do_unlink=True)

# Build every material ONCE. Reusing the same material datablocks across frames (rather
# than calling build_*_material() again each iteration) is what avoids re-triggering
# Cycles' Metal shader compiler per frame.
leaf_mat = mat_lib.build_leaf_material()
petal_mat = mat_lib.build_leaf_material(name="PetalMaterial", base_color=(0.85, 0.85, 0.82), sss_color=(0.9, 0.9, 0.88))
stem_mat = mat_lib.build_stem_material()
axis_mat = mat_lib.build_stem_material(name="AxisMaterial", vary=False)
root_mat = mat_lib.build_root_material()
silique_mat = mat_lib.build_stem_material(name="SiliqueMaterial", base_color=(0.5, 0.55, 0.25))
soil_mat = mat_lib.build_soil_material()
pot_mat = mat_lib.build_pot_material()
mat_lib.build_pot(Vector((0, 0, GROUND_Z)), POT_RADIUS, soil_mat, pot_mat)
mat_lib.setup_lighting(Vector((0, 0, MATURE_RADIUS * 0.3)), MATURE_RADIUS)

# Positive allow-list of real organ-mesh name prefixes (matches geometry.ts's namedMesh()
# convention) -- used below to find each frame's freshly-imported plant meshes for cleanup
# without touching the persistent SoilDisk/PotBody. A negative exclusion list (the v1
# approach, `name != "Plane"`) silently breaks again the next time a persistent object gets
# renamed; this doesn't need to be kept in sync with whatever the ground happens to be called.
ORGAN_PREFIXES = ("Stem_", "Root_", "LeafBlade_", "Silique_")

cam_data = bpy.data.cameras.new("Camera")
cam_obj = bpy.data.objects.new("Camera", cam_data)
bpy.context.collection.objects.link(cam_obj)
bpy.context.scene.camera = cam_obj

# Physical depth of field: focus tracks whatever this frame's camera target actually is
# (set per-frame below) -- the single highest-leverage change found for a photographic
# rather than CG look. f/3.2 was picked by rendering the same test frame at f/2.2 and f/3.2
# and comparing them directly: f/2.2 blurred enough of the plant's own structure to hurt
# legibility, f/3.2 kept the framed organ readably sharp while still softening the
# foreground/background -- an empirical choice at this scene's actual unit scale, not a
# textbook photography number assumed to transfer to an arbitrary-unit CG scene.
cam_data.dof.use_dof = True
cam_data.dof.aperture_fstop = 3.2

scene = bpy.context.scene
scene.render.engine = "CYCLES"
scene.cycles.samples = samples
scene.cycles.device = "GPU"
prefs = bpy.context.preferences.addons["cycles"].preferences
prefs.compute_device_type = "METAL"
prefs.get_devices_for_type("METAL")
for d in prefs.devices:
    d.use = True
scene.render.resolution_x = 1920
scene.render.resolution_y = 1080

t0 = time.time()
rendered = 0
for frame_idx in range(start_frame, end_frame + 1):
    out_path = f"{OUT_DIR}/frame_{frame_idx:04d}.png"
    if os.path.exists(out_path):
        continue  # resume support: don't redo a frame already on disk

    day = (frame_idx / (num_frames - 1)) * GROWTH_DAY_MAX
    subprocess.run(["npx", "tsx", "blender/export_growth_frame.ts", str(day), TMP_GLB], check=True, cwd=REPO_ROOT)

    bpy.ops.import_scene.gltf(filepath=TMP_GLB)
    new_meshes = [o for o in bpy.data.objects if o.type == "MESH" and o.name.startswith(ORGAN_PREFIXES)]
    mat_lib.apply_materials(leaf_mat, stem_mat, root_mat, petal_mat, silique_mat, axis_mat=axis_mat)

    # Frame on THIS frame's own above-ground extent (root meshes excluded -- they're mostly
    # buried, and including them would pull centering/distance toward a largely-invisible
    # extent, exactly the kind of mis-framing the fixed-mature-bbox approach had at the
    # other end of the timeline). Falls back to a tight macro framing on the collar itself
    # when nothing above-ground exists yet (day ~0, before germination is visible).
    visible = [o for o in new_meshes if not o.name.startswith("Root_")]
    corners = [o.matrix_world @ Vector(c) for o in visible for c in o.bound_box]
    if corners:
        vmin = [min(c[i] for c in corners) for i in range(3)]
        vmax = [max(c[i] for c in corners) for i in range(3)]
        frame_center = Vector([(vmin[i] + vmax[i]) / 2 for i in range(3)])
        frame_radius = max(max(vmax[i] - vmin[i] for i in range(3)) / 2, 0.05)
    else:
        frame_center = Vector((0, 0, 0))
        frame_radius = 0.08

    elevation_deg, dist_mult, lens_mm, vbias = camera_style_at_day(day)
    cam_data.lens = lens_mm
    el = math.radians(elevation_deg)
    target = frame_center + Vector((0, 0, frame_radius * vbias))

    # Clipping into the pot is only a real risk when the camera would sit AT OR BELOW the
    # pot's own rim height while ALSO being within its horizontal footprint -- comfortably
    # above the rim clears it regardless of how close horizontally, which is exactly what a
    # real overhead macro shot needs. Two earlier versions floored `dist` itself (either the
    # raw distance, or its horizontal component scaled to preserve angle); both confirmed by
    # real test renders to push a deliberately close, steep macro shot absurdly far back,
    # because scaling the whole vector to satisfy a horizontal constraint a high-enough shot
    # doesn't even need makes steep angles WORSE, not better. Flooring the vertical
    # component directly targets the actual risk instead.
    horizontal = raw_dist = frame_radius * dist_mult
    horizontal *= math.cos(el)
    vertical = raw_dist * math.sin(el)
    min_vertical_clear = POT_RADIUS * 0.5
    if vertical < min_vertical_clear and horizontal < POT_RADIUS * 1.15:
        vertical = min_vertical_clear
    dist = math.hypot(horizontal, vertical)
    el_effective = math.atan2(vertical, horizontal)

    # Slow continuous orbit: azimuth drifts across the whole animation, a real cinematic
    # move rather than a static turntable-free shot -- a technique choice, not data.
    progress = frame_idx / max(1, num_frames - 1)
    az = math.radians(20 + 40 * progress)
    cam_obj.location = target + Vector((dist * math.cos(el_effective) * math.sin(az), -dist * math.cos(el_effective) * math.cos(az), dist * math.sin(el_effective)))
    look_dir = target - cam_obj.location
    cam_obj.rotation_euler = look_dir.to_track_quat("-Z", "Y").to_euler()
    cam_data.dof.focus_distance = dist

    scene.render.filepath = out_path
    bpy.ops.render.render(write_still=True)

    # Remove this frame's imported plant objects (but not materials/lights/camera/ground)
    # before the next iteration.
    for o in new_meshes:
        mesh_data = o.data
        bpy.data.objects.remove(o, do_unlink=True)
        if mesh_data and mesh_data.users == 0:
            bpy.data.meshes.remove(mesh_data)

    rendered += 1
    elapsed = time.time() - t0
    avg = elapsed / rendered
    remaining = (end_frame - frame_idx)
    eta_min = avg * remaining / 60
    print(f"FRAME_DONE {frame_idx} day={day:.2f} elapsed={elapsed:.0f}s avg={avg:.1f}s/frame eta={eta_min:.1f}min")

print("ANIMATION_RENDER_COMPLETE")
